<!DOCTYPE html>
<html lang="ja-JP">
<head>
	<title>NASB1995</title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="_csrf_header" content="${_csrf.headerName}">
	<meta name="_csrf_token" content="${_csrf.token}">
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/bstreeview/css/bstreeview.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/customize.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
	<link rel="shortcut icon" type="image/x-icon" href="/static/favicon.ico">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Corinthia:wght@700&family=Noto+Sans+JP:wght@100..900&family=Noto+Serif+JP:wght@200..900&display=swap">
	<script type="text/javascript" src="/static/bootstrap/js/bootstrap.bundle.min.js" nonce="${nonce}"></script>
	<script type="text/javascript" src="/static/bstreeview/js/bstreeview.min.js" nonce="${nonce}"></script>
	<script type="text/javascript" src="/static/layer/neo-layer.js" nonce="${nonce}"></script>
	<script type="text/javascript" src="/static/customizes/constants.js" nonce="${nonce}"></script>
	<script type="text/javascript" src="/static/customizes/commons.js" nonce="${nonce}"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@11" nonce="${nonce}"></script>
</head>
</html>